using System;

namespace FinanceEnterprise.Entities.Finance.Models.dbo.HR
{
    public class HrEmpmstr
    {
        public string ActionCd { get; set; }
        public DateTime? Addl1 { get; set; }
        public decimal? Addl2 { get; set; }
        public string Addl3 { get; set; }
        public string Addl4 { get; set; }
        public string ApprvCd01 { get; set; }
        public string ApprvCd02 { get; set; }
        public string ApprvCd03 { get; set; }
        public string Bargunit { get; set; }
        public DateTime? Bdt { get; set; }
        public DateTime? Beg { get; set; }
        public decimal? BeneFte { get; set; }
        public string Birthplace { get; set; }
        public string Calendar { get; set; }
        public string Citizenshp { get; set; }
        public string City { get; set; }
        public string Ckdist { get; set; }
        public string ClassServ { get; set; }
        public string Country { get; set; }
        public string County { get; set; }
        public int? CreateErrors { get; set; }
        public int? CreateTime { get; set; }
        public DateTime? CreateWhen { get; set; }
        public string CreateWho { get; set; }
        public string Cycle { get; set; }
        public string DayPatch { get; set; }
        public decimal? Dayswork { get; set; }
        public string DefPay { get; set; }
        public string DefPayCd { get; set; }
        public string Department { get; set; }
        public string Dflt39 { get; set; }
        public string Disability { get; set; }
        public DateTime? Distsenr { get; set; }
        public string Division { get; set; }
        public string EMail { get; set; }
        public string EducCd01 { get; set; }
        public string EducCd02 { get; set; }
        public string EmpPin { get; set; }
        public string EmpPinhex { get; set; }
        public string EmpSwitch { get; set; }
        public DateTime? Enddt { get; set; }
        public string EntityId { get; set; }
        public string Ethnic { get; set; }
        public DateTime? Expire39 { get; set; }
        public string Ext2 { get; set; }
        public string FAdmin { get; set; }
        public string FlsaCode { get; set; }
        public string Fname { get; set; }
        public string Former { get; set; }
        public decimal? Fte { get; set; }
        public string Gender { get; set; }
        public DateTime? Hdt { get; set; }
        public string HrStatus { get; set; }
        public string Hr1 { get; set; }
        public string Hr10 { get; set; }
        public string Hr11 { get; set; }
        public string Hr12 { get; set; }
        public string Hr13 { get; set; }
        public string Hr14 { get; set; }
        public string Hr15 { get; set; }
        public string Hr16 { get; set; }
        public string Hr17 { get; set; }
        public string Hr18 { get; set; }
        public string Hr19 { get; set; }
        public string Hr2 { get; set; }
        public string Hr20 { get; set; }
        public string Hr21 { get; set; }
        public string Hr22 { get; set; }
        public string Hr23 { get; set; }
        public string Hr24 { get; set; }
        public string Hr25 { get; set; }
        public string Hr26 { get; set; }
        public string Hr27 { get; set; }
        public string Hr28 { get; set; }
        public string Hr29 { get; set; }
        public string Hr3 { get; set; }
        public string Hr30 { get; set; }
        public string Hr31 { get; set; }
        public string Hr32 { get; set; }
        public string Hr4 { get; set; }
        public string Hr5 { get; set; }
        public string Hr6 { get; set; }
        public string Hr7 { get; set; }
        public string Hr8 { get; set; }
        public string Hr9 { get; set; }
        public DateTime? Hrdate1 { get; set; }
        public DateTime? Hrdate2 { get; set; }
        public DateTime? Hrdate3 { get; set; }
        public DateTime? Hrdate4 { get; set; }
        public DateTime? Hrdate5 { get; set; }
        public DateTime? Hrdate6 { get; set; }
        public string Id { get; set; }
        public string Idauto { get; set; }
        public DateTime? Lastdaywrk { get; set; }
        public DateTime? Lastpaydt { get; set; }
        public string Lname { get; set; }
        public int? LockFlag { get; set; }
        public DateTime? Longevity { get; set; }
        public string Lumpsum { get; set; }
        public int? MiscCd01 { get; set; }
        public string Mname { get; set; }
        public decimal? MnthPaid { get; set; }
        public string Mrt { get; set; }
        public string Name { get; set; }
        public string NclbCred { get; set; }
        public decimal? Nomonths { get; set; }
        public string Notes { get; set; }
        public decimal? Numb1 { get; set; }
        public decimal? Numb2 { get; set; }
        public decimal? Numb3 { get; set; }
        public decimal? Numb4 { get; set; }
        public decimal? Numb5 { get; set; }
        public decimal? Numb6 { get; set; }
        public decimal? Numb7 { get; set; }
        public decimal? Numb8 { get; set; }
        public decimal? Numb9 { get; set; }
        public string Over40 { get; set; }
        public string PhoneCd { get; set; }
        public string PhoneCd2 { get; set; }
        public string PhoneExt { get; set; }
        public string PhoneNo { get; set; }
        public string PhoneNo2 { get; set; }
        public DateTime? Possenr { get; set; }
        public string Prefname { get; set; }
        public string PublPriv { get; set; }
        public string ReasAccom { get; set; }
        public string ReqNum { get; set; }
        public string RptFlag { get; set; }
        public short? Salannmnth { get; set; }
        public string Salute { get; set; }
        public string SelCd02 { get; set; }
        public short? SenAdj { get; set; }
        public short? SessTime { get; set; }
        public string SkillCd05 { get; set; }
        public string Ssn { get; set; }
        public string St1 { get; set; }
        public string St2 { get; set; }
        public string Stat { get; set; }
        public string State { get; set; }
        public string Suffix { get; set; }
        public string Termcode { get; set; }
        public string Termcode2 { get; set; }
        public string Type { get; set; }
        public int UniqueId { get; set; }
        public string UniqueKey { get; set; }
        public DateTime? UpdateWhen { get; set; }
        public string UpdateWho { get; set; }
        public string UserOpt1 { get; set; }
        public string UserOpt2 { get; set; }
        public string UserOpt3 { get; set; }
        public string UserOpt4 { get; set; }
        public string Veteran { get; set; }
        public string Worksite { get; set; }
        public string Zip { get; set; }
        public string Zipext { get; set; }
        public string EthnicCd { get; set; }
        public string Age { get; set; }
        public string ClassificationCd { get; set; }

    }
}
